this is the user after adding to db: ModelBase {
  attributes: 
   { id: 5,
     google_id: '116304062632694309835',
     accessToken: 'ya29.Ci9vA91EVP5x1bPH1tv1CBNdZ1A8kR4j2gzd2_TsblQL4oTqo1fiMuJ_YxP01cqMFQ',
     refreshToken: '1/DEeyCZbCypQT6-b46pPthFxmEpNVEQSvPlzTAoq1rhA',
     fullName: 'Here We Go',
     email: 'herewegoapp1@gmail.com',
     password: null,
     created_at: Sat Oct 01 2016 11:06:33 GMT-0400 (EDT),
     updated_at: Sat Oct 01 2016 11:06:33 GMT-0400 (EDT) },
  _previousAttributes: 
   { id: 5,
     google_id: '116304062632694309835',
     accessToken: 'ya29.Ci9vA91EVP5x1bPH1tv1CBNdZ1A8kR4j2gzd2_TsblQL4oTqo1fiMuJ_YxP01cqMFQ',
     refreshToken: '1/DEeyCZbCypQT6-b46pPthFxmEpNVEQSvPlzTAoq1rhA',
     fullName: 'Here We Go',
     email: 'herewegoapp1@gmail.com',
     password: null,
     created_at: Sat Oct 01 2016 11:06:33 GMT-0400 (EDT),
     updated_at: Sat Oct 01 2016 11:06:33 GMT-0400 (EDT) },
  changed: {},
  relations: {},
  cid: 'c1',
  _knex: null,
  id: 5 }
user profile before sift { id: '116304062632694309835',
  displayName: 'Here We Go',
  name: { familyName: 'Go', givenName: 'Here We' },
  emails: [ { value: 'herewegoapp1@gmail.com', type: 'account' } ],
  photos: [ { value: 'https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg?sz=50' } ],
  gender: undefined,
  provider: 'google',
  _raw: '{\n "kind": "plus#person",\n "etag": "\\"xw0en60W6-NurXn4VBU-CMjSPEw/2CYovAynvCVkM8VE-t3g2gsCVeg\\"",\n "emails": [\n  {\n   "value": "herewegoapp1@gmail.com",\n   "type": "account"\n  }\n ],\n "objectType": "person",\n "id": "116304062632694309835",\n "displayName": "Here We Go",\n "name": {\n  "familyName": "Go",\n  "givenName": "Here We"\n },\n "image": {\n  "url": "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg?sz=50",\n  "isDefault": true\n },\n "isPlusUser": false,\n "language": "en",\n "verified": false\n}\n',
  _json: 
   { kind: 'plus#person',
     etag: '"xw0en60W6-NurXn4VBU-CMjSPEw/2CYovAynvCVkM8VE-t3g2gsCVeg"',
     emails: [ [Object] ],
     objectType: 'person',
     id: '116304062632694309835',
     displayName: 'Here We Go',
     name: { familyName: 'Go', givenName: 'Here We' },
     image: 
      { url: 'https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg?sz=50',
        isDefault: true },
     isPlusUser: false,
     language: 'en',
     verified: false } }
USER IN DATABASE
email connections: []
new user response { username: 'herewegoapp1@gmail.com', user_id: 791651 }
>>> ADDING PAYLOAD TO DB <<<
item #0 { username: 'herewegoapp1@gmail.com',
  domain: 'hotel',
  gmid: '1546995204890465085',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475329594,
  mime_id: 'df254948f7535bd1eefd6c88b45b6119',
  host: 'imap.gmail.com',
  sift_id: 1661536,
  payload: 
   { reservationFor: 
      { '@type': 'LodgingBusiness',
        name: 'Courtyard Orlando Lake Buena Vista in the Marriott Village',
        telephone: '',
        'x-days': '6',
        address: '8623 Vineland Avenue, Orlando, Florida 32821 USA' },
     reservationStatus: 'http://schema.org/ReservationConfirmed',
     broker: { '@type': 'Organization', name: 'The Ritz-Carlton' },
     checkoutTime: '2014-06-20T12:00:00',
     reservationId: '81470798',
     '@context': 'http://schema.org',
     checkinTime: '2014-06-14T15:00:00',
     '@type': 'LodgingReservation' },
  mid: '15',
  fid: '[Gmail]/All Mail' }
item #0payload: [object Object]
////<---===--------===----------===---------===--->
item #1 { username: 'herewegoapp1@gmail.com',
  domain: 'hotel',
  gmid: '1547002609289823578',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475336656,
  mime_id: 'aabb237075a14d533b44f9ad2c9318f5',
  host: 'imap.gmail.com',
  sift_id: 1661537,
  payload: 
   { reservationFor: 
      { '@type': 'LodgingBusiness',
        name: 'Revel',
        telephone: '',
        'x-days': '1',
        address: '' },
     reservationStatus: 'http://schema.org/ReservationConfirmed',
     broker: { '@type': 'Organization', name: 'Expedia' },
     checkoutTime: '2014-03-23T00:00:00',
     reservationId: '169491662578',
     '@context': 'http://schema.org',
     checkinTime: '2014-03-22T16:00:00',
     '@type': 'LodgingReservation' },
  mid: '18',
  fid: '[Gmail]/All Mail' }
item #1payload: [object Object]
//<---===--------===----------===---------===--->
item #2 { username: 'herewegoapp1@gmail.com',
  domain: 'purchase',
  gmid: '1546995116422255147',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475329510,
  mime_id: 'd51e1dcc9c3528ff04bc276098f4364f',
  host: 'imap.gmail.com',
  sift_id: 1661542,
  payload: 
   { description: 'Your La Quinta Hotel reservation',
     seller: { '@type': 'Organization', name: 'La Quinta' },
     orderNumber: '3184537495',
     broker: { '@type': 'Organization', name: 'La Quinta' },
     acceptedOffer: [],
     'x-price': '136.80',
     'x-paymentScheduled': 'n',
     '@context': 'http://schema.org',
     partOfInvoice: 
      { totalPaymentDue: [Object],
        paymentStatus: '',
        'x-paymentMade': [Object],
        'x-balanceDue': [Object],
        paymentDueDate: '',
        confirmationNumber: '',
        '@type': 'Invoice' },
     'x-subTotal': '',
     '@type': 'Order' },
  mid: '14',
  fid: '[Gmail]/All Mail' }
item #2payload: [object Object]
//<---===--------===----------===---------===--->
item #3 { username: 'herewegoapp1@gmail.com',
  domain: 'hotel',
  gmid: '1546995116422255147',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475329510,
  mime_id: 'd51e1dcc9c3528ff04bc276098f4364f',
  host: 'imap.gmail.com',
  sift_id: 1661544,
  payload: 
   { reservationFor: 
      { '@type': 'LodgingBusiness',
        name: 'La Quinta Inn & Suites Garden City',
        telephone: '516 - 705-9000',
        'x-days': '1',
        address: '821 Stewart Ave Garden City, NY 11530' },
     reservationStatus: 'http://schema.org/ReservationConfirmed',
     broker: { '@type': 'Organization', name: 'La Quinta' },
     checkoutTime: '2015-02-14T12:00:00',
     reservationId: '3184537495',
     '@context': 'http://schema.org',
     checkinTime: '2015-02-13T15:00:00',
     '@type': 'LodgingReservation' },
  mid: '14',
  fid: '[Gmail]/All Mail' }
item #3payload: [object Object]
//<---===--------===----------===---------===--->
item #4 { username: 'herewegoapp1@gmail.com',
  domain: 'purchase',
  gmid: '1546995031769145340',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475329429,
  mime_id: '83c4d443702c266486d5cbd097acd905',
  host: 'imap.gmail.com',
  sift_id: 1661547,
  payload: 
   { description: 'Your Delta Flight reservation',
     seller: { '@type': 'Organization', name: 'Delta' },
     orderNumber: 'HRX2ZU',
     broker: { '@type': 'Organization', name: 'Delta' },
     acceptedOffer: [],
     'x-price': '253.00',
     'x-paymentScheduled': 'n',
     '@context': 'http://schema.org',
     partOfInvoice: 
      { totalPaymentDue: [Object],
        paymentStatus: '',
        'x-paymentMade': [Object],
        'x-balanceDue': [Object],
        paymentDueDate: '',
        confirmationNumber: '',
        '@type': 'Invoice' },
     'x-subTotal': '',
     '@type': 'Order' },
  mid: '13',
  fid: '[Gmail]/All Mail' }
item #4payload: [object Object]
//<---===--------===----------===---------===--->
item #5 { username: 'herewegoapp1@gmail.com',
  domain: 'flight',
  gmid: '1546995031769145340',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475329429,
  mime_id: '83c4d443702c266486d5cbd097acd905',
  host: 'imap.gmail.com',
  sift_id: 1661548,
  payload: 
   { reservationFor: [ [Object], [Object] ],
     reservationStatus: 'http://schema.org/ReservationConfirmed',
     broker: { '@type': 'Organization', name: 'Delta' },
     reservedTicket: [ [Object] ],
     reservationId: 'HRX2ZU',
     '@context': 'http://schema.org',
     '@type': 'FlightReservation' },
  mid: '13',
  fid: '[Gmail]/All Mail' }
item #5payload: [object Object]
//<---===--------===----------===---------===--->
item #6 { username: 'herewegoapp1@gmail.com',
  domain: 'purchase',
  gmid: '1546732545154740727',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475079103,
  mime_id: '984b0d97d525e236e0aef17c378eaf51',
  host: 'imap.gmail.com',
  sift_id: 1661549,
  payload: 
   { description: 'Your Expedia receipt',
     seller: { '@type': 'Organization', name: 'Expedia' },
     orderNumber: '176482113984',
     broker: { '@type': 'Organization', name: 'Expedia' },
     acceptedOffer: [],
     'x-price': '$805.60',
     'x-paymentScheduled': 'n',
     '@context': 'http://schema.org',
     partOfInvoice: 
      { totalPaymentDue: [Object],
        paymentStatus: '',
        'x-paymentMade': [Object],
        'x-balanceDue': [Object],
        paymentDueDate: '',
        confirmationNumber: '',
        '@type': 'Invoice' },
     'x-subTotal': '',
     '@type': 'Order' },
  mid: '8',
  fid: '[Gmail]/All Mail' }
item #6payload: [object Object]
//<---===--------===----------===---------===--->
item #7 { username: 'herewegoapp1@gmail.com',
  domain: 'purchase',
  gmid: '1546732205747224515',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475078779,
  mime_id: 'a7d53c5a0e6bd074d6b4832ae9ab3770',
  host: 'imap.gmail.com',
  sift_id: 1661550,
  payload: 
   { description: 'Your Expedia receipt',
     seller: { '@type': 'Organization', name: 'Expedia' },
     orderNumber: '7155225693278',
     broker: { '@type': 'Organization', name: 'Expedia' },
     acceptedOffer: [],
     'x-price': '$206.20',
     'x-paymentScheduled': 'n',
     '@context': 'http://schema.org',
     partOfInvoice: 
      { totalPaymentDue: [Object],
        paymentStatus: '',
        'x-paymentMade': [Object],
        'x-balanceDue': [Object],
        paymentDueDate: '',
        confirmationNumber: '',
        '@type': 'Invoice' },
     'x-subTotal': '',
     '@type': 'Order' },
  mid: '2',
  fid: '[Gmail]/All Mail' }
item #7payload: [object Object]
//<---===--------===----------===---------===--->
item #8 { username: 'herewegoapp1@gmail.com',
  domain: 'hotel',
  gmid: '1546732545154740727',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475079103,
  mime_id: '984b0d97d525e236e0aef17c378eaf51',
  host: 'imap.gmail.com',
  sift_id: 1661551,
  payload: 
   { reservationFor: 
      { '@type': 'LodgingBusiness',
        name: 'Despotiko Hotel',
        telephone: '',
        'x-days': '2',
        address: '' },
     reservationStatus: 'http://schema.org/ReservationConfirmed',
     broker: { '@type': 'Organization', name: 'Expedia' },
     checkoutTime: '2014-07-23T00:00:00',
     reservationId: '176482113984',
     '@context': 'http://schema.org',
     checkinTime: '2014-07-21T14:00:00',
     '@type': 'LodgingReservation' },
  mid: '8',
  fid: '[Gmail]/All Mail' }
item #8payload: [object Object]
//<---===--------===----------===---------===--->
item #9 { username: 'herewegoapp1@gmail.com',
  domain: 'flight',
  gmid: '1546732205747224515',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475078779,
  mime_id: 'a7d53c5a0e6bd074d6b4832ae9ab3770',
  host: 'imap.gmail.com',
  sift_id: 1661552,
  payload: 
   { reservationFor: [ [Object], [Object] ],
     reservationStatus: 'http://schema.org/ReservationConfirmed',
     broker: { '@type': 'Organization', name: 'Expedia' },
     reservedTicket: [ [Object], [Object], [Object], [Object] ],
     reservationId: '7155225693278',
     programMembershipUsed: [ [Object], [Object] ],
     '@context': 'http://schema.org',
     '@type': 'FlightReservation' },
  mid: '2',
  fid: '[Gmail]/All Mail' }
item #9payload: [object Object]
//<---===--------===----------===---------===--->
item #10 { username: 'herewegoapp1@gmail.com',
  domain: 'purchase',
  gmid: '1546732605372691799',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475079160,
  mime_id: '79a48d6aab21c2cd29fb6ed3b850d3d0',
  host: 'imap.gmail.com',
  sift_id: 1661554,
  payload: 
   { description: 'Your Expedia receipt',
     seller: { '@type': 'Organization', name: 'Expedia' },
     orderNumber: '169491662578',
     broker: { '@type': 'Organization', name: 'Expedia' },
     acceptedOffer: [],
     'x-price': '$320.28',
     'x-paymentScheduled': 'n',
     '@context': 'http://schema.org',
     partOfInvoice: 
      { totalPaymentDue: [Object],
        paymentStatus: '',
        'x-paymentMade': [Object],
        'x-balanceDue': [Object],
        paymentDueDate: '',
        confirmationNumber: '',
        '@type': 'Invoice' },
     'x-subTotal': '',
     '@type': 'Order' },
  mid: '10',
  fid: '[Gmail]/All Mail' }
item #10payload: [object Object]
//<---===--------===----------===---------===--->
item #11 { username: 'herewegoapp1@gmail.com',
  domain: 'hotel',
  gmid: '1546732605372691799',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475079160,
  mime_id: '79a48d6aab21c2cd29fb6ed3b850d3d0',
  host: 'imap.gmail.com',
  sift_id: 1661555,
  payload: 
   { reservationFor: 
      { '@type': 'LodgingBusiness',
        name: 'Revel',
        telephone: '',
        'x-days': '1',
        address: '' },
     reservationStatus: 'http://schema.org/ReservationConfirmed',
     broker: { '@type': 'Organization', name: 'Expedia' },
     checkoutTime: '2014-03-23T00:00:00',
     reservationId: '169491662578',
     '@context': 'http://schema.org',
     checkinTime: '2014-03-22T16:00:00',
     '@type': 'LodgingReservation' },
  mid: '10',
  fid: '[Gmail]/All Mail' }
item #11payload: [object Object]
//<---===--------===----------===---------===--->
item #12 { username: 'herewegoapp1@gmail.com',
  domain: 'flight',
  gmid: '1547002731098525649',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475336771,
  mime_id: '94ed3f2f20540c99d7ccb99a9e7c013e',
  host: 'imap.gmail.com',
  sift_id: 1661558,
  payload: 
   { reservationFor: [ [Object], [Object] ],
     reservationStatus: 'http://schema.org/ReservationConfirmed',
     broker: { '@type': 'Organization', name: 'Expedia' },
     reservedTicket: [ [Object], [Object], [Object], [Object] ],
     reservationId: 'G4NQID',
     '@context': 'http://schema.org',
     '@type': 'FlightReservation' },
  mid: '20',
  fid: '[Gmail]/All Mail' }
item #12payload: [object Object]
//<---===--------===----------===---------===--->
item #13 { username: 'herewegoapp1@gmail.com',
  domain: 'rentalcar',
  gmid: '1546995293744570297',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475329679,
  mime_id: '4358acb5ad85afd28876e8138ea6f549',
  host: 'imap.gmail.com',
  sift_id: 1661559,
  payload: 
   { reservationFor: { '@type': 'Car', name: 'Dodge Grand Caravan' },
     dropoffLocation: 
      { '@type': 'Place',
        name: '',
        address: '1 Airport Blvd Orlando, FL US 32812-3023' },
     reservationStatus: 'http://schema.org/ReservationConfirmed',
     provider: { '@type': 'Organization', name: 'Hertz Rent-a-Car' },
     underName: { '@type': 'Person', name: 'Jennie Wallace' },
     reservationId: 'G16413130B7',
     pickupTime: '2014-06-14T16:00:00',
     pickupLocation: 
      { '@type': 'Place',
        name: '',
        address: '1 Airport Blvd Orlando, FL US 32812-3023' },
     '@context': 'http://schema.org',
     dropoffTime: '2014-06-20T10:00:00',
     '@type': 'RentalCarReservation' },
  mid: '17',
  fid: '[Gmail]/All Mail' }
item #13payload: [object Object]
//<---===--------===----------===---------===--->
item #14 { username: 'herewegoapp1@gmail.com',
  domain: 'purchase',
  gmid: '1546732389269003592',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475078954,
  mime_id: '1afc159cc67aa08c85f55a5c407ec066',
  host: 'imap.gmail.com',
  sift_id: 1661560,
  payload: 
   { description: 'Your Expedia receipt',
     seller: { '@type': 'Organization', name: 'Expedia' },
     orderNumber: '7121323108678',
     broker: { '@type': 'Organization', name: 'Expedia' },
     acceptedOffer: [],
     'x-price': '$750.40',
     'x-paymentScheduled': 'n',
     '@context': 'http://schema.org',
     partOfInvoice: 
      { totalPaymentDue: [Object],
        paymentStatus: '',
        'x-paymentMade': [Object],
        'x-balanceDue': [Object],
        paymentDueDate: '',
        confirmationNumber: '',
        '@type': 'Invoice' },
     'x-subTotal': '',
     '@type': 'Order' },
  mid: '4',
  fid: '[Gmail]/All Mail' }
item #14payload: [object Object]
//<---===--------===----------===---------===--->
item #15 { username: 'herewegoapp1@gmail.com',
  domain: 'flight',
  gmid: '1546732389269003592',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475078954,
  mime_id: '1afc159cc67aa08c85f55a5c407ec066',
  host: 'imap.gmail.com',
  sift_id: 1661561,
  payload: 
   { reservationFor: [ [Object], [Object] ],
     reservationStatus: 'http://schema.org/ReservationConfirmed',
     broker: { '@type': 'Organization', name: 'Expedia' },
     reservedTicket: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     reservationId: '7121323108678',
     programMembershipUsed: [ [Object], [Object], [Object], [Object] ],
     '@context': 'http://schema.org',
     '@type': 'FlightReservation' },
  mid: '4',
  fid: '[Gmail]/All Mail' }
item #15payload: [object Object]
//<---===--------===----------===---------===--->
item #16 { username: 'herewegoapp1@gmail.com',
  domain: 'purchase',
  gmid: '1546732581005476190',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475079137,
  mime_id: '2906094b6ce684ead730d3fb933dc113',
  host: 'imap.gmail.com',
  sift_id: 1661563,
  payload: 
   { description: 'Your Expedia receipt',
     seller: { '@type': 'Organization', name: 'Expedia' },
     orderNumber: '170767281307',
     broker: { '@type': 'Organization', name: 'Expedia' },
     acceptedOffer: [],
     'x-price': '$925.06',
     'x-paymentScheduled': 'n',
     '@context': 'http://schema.org',
     partOfInvoice: 
      { totalPaymentDue: [Object],
        paymentStatus: '',
        'x-paymentMade': [Object],
        'x-balanceDue': [Object],
        paymentDueDate: '',
        confirmationNumber: '',
        '@type': 'Invoice' },
     'x-subTotal': '',
     '@type': 'Order' },
  mid: '9',
  fid: '[Gmail]/All Mail' }
item #16payload: [object Object]
//<---===--------===----------===---------===--->
item #17 { username: 'herewegoapp1@gmail.com',
  domain: 'flight',
  gmid: '1546732581005476190',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475079137,
  mime_id: '2906094b6ce684ead730d3fb933dc113',
  host: 'imap.gmail.com',
  sift_id: 1661564,
  payload: 
   { reservationFor: [ [Object], [Object] ],
     reservationStatus: 'http://schema.org/ReservationConfirmed',
     broker: { '@type': 'Organization', name: 'Expedia' },
     reservedTicket: [ [Object], [Object], [Object], [Object] ],
     reservationId: '170767281307',
     programMembershipUsed: [ [Object], [Object] ],
     '@context': 'http://schema.org',
     '@type': 'FlightReservation' },
  mid: '9',
  fid: '[Gmail]/All Mail' }
item #17payload: [object Object]
//<---===--------===----------===---------===--->
item #18 { username: 'herewegoapp1@gmail.com',
  domain: 'purchase',
  gmid: '1546732263138916545',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475078834,
  mime_id: 'f7cebadb109fbbbc8d58da8d9d1d6d9c',
  host: 'imap.gmail.com',
  sift_id: 1661568,
  payload: 
   { description: 'Your Expedia order',
     seller: { '@type': 'Organization', name: 'Expedia' },
     orderNumber: '1123913044066',
     broker: { '@type': 'Organization', name: 'Expedia' },
     acceptedOffer: [ [Object] ],
     'x-price': '$2.07',
     'x-paymentScheduled': 'n',
     '@context': 'http://schema.org',
     partOfInvoice: 
      { totalPaymentDue: [Object],
        paymentStatus: '',
        'x-paymentMade': [Object],
        'x-balanceDue': [Object],
        paymentDueDate: '',
        confirmationNumber: '',
        '@type': 'Invoice' },
     'x-subTotal': '',
     '@type': 'Order' },
  mid: '3',
  fid: '[Gmail]/All Mail' }
item #18payload: [object Object]
//<---===--------===----------===---------===--->
item #19 { username: 'herewegoapp1@gmail.com',
  domain: 'hotel',
  gmid: '1546732263138916545',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475078834,
  mime_id: 'f7cebadb109fbbbc8d58da8d9d1d6d9c',
  host: 'imap.gmail.com',
  sift_id: 1661569,
  payload: 
   { reservationFor: 
      { '@type': 'LodgingBusiness',
        name: 'NU Hotel Brooklyn',
        telephone: '1 (718) 852-8585',
        'x-days': '1',
        address: '85 Smith St, Brooklyn, NY, 11201 United States of America' },
     reservationStatus: 'http://schema.org/ReservationConfirmed',
     broker: { '@type': 'Organization', name: 'Expedia' },
     checkoutTime: '2015-12-24T12:00:00',
     reservationId: '1123913044066',
     '@context': 'http://schema.org',
     checkinTime: '2015-12-23T15:00:00',
     '@type': 'LodgingReservation' },
  mid: '3',
  fid: '[Gmail]/All Mail' }
item #19payload: [object Object]
//<---===--------===----------===---------===--->
item #20 { username: 'herewegoapp1@gmail.com',
  domain: 'purchase',
  gmid: '1546995241294074224',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475329629,
  mime_id: '033a53d047cf0ead8b557236e5a72394',
  host: 'imap.gmail.com',
  sift_id: 1661570,
  payload: 
   { description: 'Your Hilton Hotel reservation',
     seller: { '@type': 'Organization', name: 'Hilton' },
     orderNumber: '',
     broker: { '@type': 'Organization', name: 'Hilton' },
     acceptedOffer: [],
     'x-price': '223.85',
     'x-paymentScheduled': 'n',
     '@context': 'http://schema.org',
     partOfInvoice: 
      { totalPaymentDue: [Object],
        paymentStatus: '',
        'x-paymentMade': [Object],
        'x-balanceDue': [Object],
        paymentDueDate: '',
        confirmationNumber: '',
        '@type': 'Invoice' },
     'x-subTotal': '',
     '@type': 'Order' },
  mid: '16',
  fid: '[Gmail]/All Mail' }
item #20payload: [object Object]
//<---===--------===----------===---------===--->
item #21 { username: 'herewegoapp1@gmail.com',
  domain: 'hotel',
  gmid: '1546995241294074224',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475329629,
  mime_id: '033a53d047cf0ead8b557236e5a72394',
  host: 'imap.gmail.com',
  sift_id: 1661571,
  payload: 
   { reservationFor: 
      { '@type': 'LodgingBusiness',
        name: 'Homewood Suites by Hilton Mahwah',
        telephone: '',
        'x-days': '1',
        address: '' },
     reservationStatus: 'http://schema.org/ReservationConfirmed',
     broker: { '@type': 'Organization', name: 'Hilton' },
     checkoutTime: '2010-09-05T12:00:00',
     reservationId: '84186395',
     '@context': 'http://schema.org',
     checkinTime: '2010-09-04T15:00:00',
     '@type': 'LodgingReservation' },
  mid: '16',
  fid: '[Gmail]/All Mail' }
item #21payload: [object Object]
//<---===--------===----------===---------===--->
item #22 { username: 'herewegoapp1@gmail.com',
  domain: 'purchase',
  gmid: '1546732428375512755',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475078991,
  mime_id: 'b5674b5d8cd73a280e33092ab7f9d407',
  host: 'imap.gmail.com',
  sift_id: 1661572,
  payload: 
   { description: 'Your Expedia receipt',
     seller: { '@type': 'Organization', name: 'Expedia' },
     orderNumber: '776479586113',
     broker: { '@type': 'Organization', name: 'Expedia' },
     acceptedOffer: [],
     'x-price': '$345.14',
     'x-paymentScheduled': 'n',
     '@context': 'http://schema.org',
     partOfInvoice: 
      { totalPaymentDue: [Object],
        paymentStatus: '',
        'x-paymentMade': [Object],
        'x-balanceDue': [Object],
        paymentDueDate: '',
        confirmationNumber: '',
        '@type': 'Invoice' },
     'x-subTotal': '',
     '@type': 'Order' },
  mid: '5',
  fid: '[Gmail]/All Mail' }
item #22payload: [object Object]
//<---===--------===----------===---------===--->
item #23 { username: 'herewegoapp1@gmail.com',
  domain: 'hotel',
  gmid: '1546732428375512755',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475078991,
  mime_id: 'b5674b5d8cd73a280e33092ab7f9d407',
  host: 'imap.gmail.com',
  sift_id: 1661573,
  payload: 
   { reservationFor: 
      { '@type': 'LodgingBusiness',
        name: 'Novotel Montreal Centre',
        telephone: '',
        'x-days': '2',
        address: '' },
     reservationStatus: 'http://schema.org/ReservationConfirmed',
     broker: { '@type': 'Organization', name: 'Expedia' },
     checkoutTime: '2014-11-16T00:00:00',
     reservationId: '776479586113',
     '@context': 'http://schema.org',
     checkinTime: '2014-11-14T15:00:00',
     '@type': 'LodgingReservation' },
  mid: '5',
  fid: '[Gmail]/All Mail' }
item #23payload: [object Object]
//<---===--------===----------===---------===--->
item #24 { username: 'herewegoapp1@gmail.com',
  domain: 'purchase',
  gmid: '1546732513155988501',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475079071,
  mime_id: 'b76dfb9c5a479f6d2fc7c66bea7549d5',
  host: 'imap.gmail.com',
  sift_id: 1661576,
  payload: 
   { description: 'Your Expedia receipt',
     seller: { '@type': 'Organization', name: 'Expedia' },
     orderNumber: '175849915665',
     broker: { '@type': 'Organization', name: 'Expedia' },
     acceptedOffer: [],
     'x-price': '$3121.20',
     'x-paymentScheduled': 'n',
     '@context': 'http://schema.org',
     partOfInvoice: 
      { totalPaymentDue: [Object],
        paymentStatus: '',
        'x-paymentMade': [Object],
        'x-balanceDue': [Object],
        paymentDueDate: '',
        confirmationNumber: '',
        '@type': 'Invoice' },
     'x-subTotal': '',
     '@type': 'Order' },
  mid: '7',
  fid: '[Gmail]/All Mail' }
item #24payload: [object Object]
//<---===--------===----------===---------===--->
item #25 { username: 'herewegoapp1@gmail.com',
  domain: 'flight',
  gmid: '1546732513155988501',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475079071,
  mime_id: 'b76dfb9c5a479f6d2fc7c66bea7549d5',
  host: 'imap.gmail.com',
  sift_id: 1661577,
  payload: 
   { reservationFor: [ [Object], [Object], [Object], [Object], [Object] ],
     reservationStatus: 'http://schema.org/ReservationConfirmed',
     broker: { '@type': 'Organization', name: 'Expedia' },
     reservedTicket: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     reservationId: '175849915665',
     programMembershipUsed: [ [Object], [Object] ],
     '@context': 'http://schema.org',
     '@type': 'FlightReservation' },
  mid: '7',
  fid: '[Gmail]/All Mail' }
item #25payload: [object Object]
//<---===--------===----------===---------===--->
item #26 { username: 'herewegoapp1@gmail.com',
  domain: 'purchase',
  gmid: '1546732477416456826',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475079038,
  mime_id: '295ca31725eab29d481f3875d4e430b9',
  host: 'imap.gmail.com',
  sift_id: 1661578,
  payload: 
   { description: 'Your Expedia receipt',
     seller: { '@type': 'Organization', name: 'Expedia' },
     orderNumber: '185565338793',
     broker: { '@type': 'Organization', name: 'Expedia' },
     acceptedOffer: [],
     'x-price': '$2514.42',
     'x-paymentScheduled': 'n',
     '@context': 'http://schema.org',
     partOfInvoice: 
      { totalPaymentDue: [Object],
        paymentStatus: '',
        'x-paymentMade': [Object],
        'x-balanceDue': [Object],
        paymentDueDate: '',
        confirmationNumber: '',
        '@type': 'Invoice' },
     'x-subTotal': '',
     '@type': 'Order' },
  mid: '22',
  fid: '[Gmail]/All Mail' }
item #26payload: [object Object]
//<---===--------===----------===---------===--->
item #27 { username: 'herewegoapp1@gmail.com',
  domain: 'hotel',
  gmid: '1546732477416456826',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475079038,
  mime_id: '295ca31725eab29d481f3875d4e430b9',
  host: 'imap.gmail.com',
  sift_id: 1661579,
  payload: 
   { reservationFor: 
      { '@type': 'LodgingBusiness',
        name: 'ME Cancun - Complete ME All Inclusive',
        telephone: '52 (998) 8812500',
        'x-days': '4',
        address: 'Boulevard Kukulkan Km 12, Cancun, QROO, 77500 Mexico' },
     reservationStatus: 'http://schema.org/ReservationConfirmed',
     broker: { '@type': 'Organization', name: 'Expedia' },
     checkoutTime: '2014-11-07T00:00:00',
     reservationId: '185565338793',
     '@context': 'http://schema.org',
     checkinTime: '2014-11-03T15:00:00',
     '@type': 'LodgingReservation' },
  mid: '22',
  fid: '[Gmail]/All Mail' }
item #27payload: [object Object]
//<---===--------===----------===---------===--->
item #28 { username: 'herewegoapp1@gmail.com',
  domain: 'flight',
  gmid: '1546732477416456826',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475079038,
  mime_id: '295ca31725eab29d481f3875d4e430b9',
  host: 'imap.gmail.com',
  sift_id: 1661580,
  payload: 
   { reservationFor: [ [Object], [Object] ],
     reservationStatus: 'http://schema.org/ReservationConfirmed',
     broker: { '@type': 'Organization', name: 'Expedia' },
     reservedTicket: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
     reservationId: '185565338793',
     programMembershipUsed: [ [Object], [Object], [Object] ],
     '@context': 'http://schema.org',
     '@type': 'FlightReservation' },
  mid: '22',
  fid: '[Gmail]/All Mail' }
item #28payload: [object Object]
//<---===--------===----------===---------===--->
item #29 { username: 'herewegoapp1@gmail.com',
  domain: 'flight',
  gmid: '1546994973664652330',
  account_id: 'herewegoapp1@gmail.com',
  email_time: 1475329373,
  mime_id: '74b391f525edbb802e3221962590cb3c',
  host: 'imap.gmail.com',
  sift_id: 1661581,
  payload: 
   { reservationFor: [ [Object], [Object] ],
     reservationStatus: 'http://schema.org/ReservationConfirmed',
     broker: { '@type': 'Organization', name: 'Delta' },
     reservedTicket: [ [Object] ],
     reservationId: 'HRX2ZU',
     '@context': 'http://schema.org',
     '@type': 'FlightReservation' },
  mid: '12',
  fid: '[Gmail]/All Mail' }
item #29payload: [object Object]
//<---===--------===----------===---------===--->
